#PBS -l nodes=4:nehalem:ppn=8
#PBS -l walltime=00:01:00
#PBS -l mem=1gb
#PBS -N prefix_sum_mpi_32
#PBS -S /bin/bash
#PBS -j oe
#

# $PBS_O_WORKDIR is the directory from which the job was submitted
cd $PBS_O_WORKDIR

mpirun -np 32 ./prefix_sum.x 1000 1000

# output from the runs will be in prefix_sum_mpi_32.o#### where #### is the job id.
#---------------- end of job file --------------------------
